; Biekdafreak - Purple Drank
[purple]
text               = FFFFFF
subtext            = BFBFBF
main               = 000000
sidebar            = 000000
player             = 000000
card               = 744DA9
shadow             = 000000
selected-row       = 744DA9
button             = 744DA9
button-active      = 8764B8
button-disabled    = 3F3F3F
tab-active         = 744DA9
notification       = 744DA9
notification-error = E81123
misc               = FFFFFF
